CREATE PROCEDURE  GetChiTietPhieuMuc
	@id INT
AS
BEGIN

	SET NOCOUNT ON;
	SELECT ct.ID_MUC, nvgui.MA_NV AS MA_NV_GUI, nvgui.TEN_NV AS TEN_NV_GUI, nvgui.DON_VI AS DON_VI, nvnhan.MA_NV AS MA_NV_NHAN, nvnhan.TEN_NV AS TEN_NV_NHAN,
	ct.TEN_HOP_MUC, ct.TINH_TRANG, pm.NGAY_GUI, pm.NGAY_SUA_XONG, pm.NGAY_TRA, ct.GHI_CHU, pm.TRANG_THAI_PHIEU   
	FROM dbo.PHIEUMUC pm INNER JOIN dbo.CHITIETMUC ct ON ct.ID_MUC = pm.ID_MUC
	INNER JOIN dbo.NHANVIEN nvgui ON nvgui.MA_NV = pm.MA_NV_GUI
	LEFT JOIN dbo.NHANVIEN nvnhan ON nvnhan.MA_NV = pm.MA_NV_NHAN
	WHERE ct.ID_MUC = @id
	
	
END
