
CREATE PROCEDURE  GetTraCuuPhieuSua
	
AS
BEGIN

	SET NOCOUNT ON;
	SELECT ps.ID_PHIEU, ps.NGAY_TAO, nv.TEN_NV, nv.DON_VI, ctsua.TEN_PC,ctsua.THIET_BI_KHAC,ps.TRANG_THAI_PHIEU FROM dbo.CHITIETSUA ctsua 
	INNER JOIN dbo.PHIEUSUA ps ON ps.ID_PHIEU = ctsua.ID_PHIEU
	INNER JOIN dbo.NHANVIEN nv ON nv.MA_NV = ps.MA_NV
	
END
