CREATE TABLE [dbo].[CHITIETSUA] (
    [ID_CHITIET]    INT            IDENTITY (100, 1) NOT NULL,
    [ID_PHIEU]      INT            NULL,
    [TEN_PC]        NVARCHAR (50)  NULL,
    [ACCOUNT_NAMES] VARCHAR (50)   NULL,
    [ACCOUNT_PASS]  VARCHAR (100)  NULL,
    [THIET_BI_KHAC] NVARCHAR (50)  NULL,
    [TINH_TRANG]    NVARCHAR (200) NULL,
    [GHI_CHU]       NVARCHAR (200) NULL,
    [LOAI_SUA_CHUA] NVARCHAR (100) NULL,
    [SDT]           VARCHAR (15)   NULL,
    PRIMARY KEY CLUSTERED ([ID_CHITIET] ASC),
    FOREIGN KEY ([ID_PHIEU]) REFERENCES [dbo].[PHIEUSUA] ([ID_PHIEU])
);


GO
CREATE NONCLUSTERED INDEX [id_phieu]
    ON [dbo].[CHITIETSUA]([ID_PHIEU] ASC)
    INCLUDE([TEN_PC], [ACCOUNT_NAMES], [ACCOUNT_PASS], [LOAI_SUA_CHUA], [SDT]);

