CREATE TABLE [dbo].[CHITIETMUC] (
    [ID_CHITIET]  INT            IDENTITY (100, 1) NOT NULL,
    [ID_MUC]      INT            NULL,
    [TEN_HOP_MUC] NVARCHAR (50)  NULL,
    [LOAI_MAY_IN] NVARCHAR (50)  NULL,
    [GHI_CHU]     NVARCHAR (100) NULL,
    [TINH_TRANG]  NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([ID_CHITIET] ASC),
    FOREIGN KEY ([ID_MUC]) REFERENCES [dbo].[PHIEUMUC] ([ID_MUC])
);


GO
CREATE NONCLUSTERED INDEX [id_muc]
    ON [dbo].[CHITIETMUC]([ID_MUC] ASC)
    INCLUDE([LOAI_MAY_IN], [GHI_CHU], [TINH_TRANG]);

